---
- import_tasks: release_notes.yml 
  tags: qm_customizations_release_notes
  when: release_notes is defined and release_notes

- import_tasks: shared_folder.yml 
  tags: qm_customizations_shared_folder

- import_tasks: global_bashrc.yml 
  tags: qm_customizations_global_bashrc

- import_tasks: folders.yml 
  tags: qm_customizations_folders

- name: gui-related tasks
  tags: qm_customizations_gui
  block:
    - include_tasks: gui-ubuntu-16.04.yml
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
    - include_tasks: gui-ubuntu-18.04.yml
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04'
    - import_tasks: faq.yml
  when: not qm_customizations_headless

- meta: flush_handlers

