---
- import_tasks: release_notes.yml
  tags: qm_customizations_release_notes
  when: release_notes is defined and release_notes

- import_tasks: global_bashrc.yml
  tags: qm_customizations_global_bashrc

- import_tasks: folders.yml
  tags: qm_customizations_folders
